# -*- coding: utf-8 -*-
"""Face recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JpsOO1MAuZ0J44FvnZx5Agg3C8wF2iq3

##Assignment-9 
Chembeti Munijayanth-19MIM10025
"""

# Commented out IPython magic to ensure Python compatibility.
import cv2
import numpy as np 
# %matplotlib inline 
from matplotlib import pyplot as plt

from google.colab import files
files.upload()

!wget --no-check-certificate \
    https://raw.githubusercontent.com/computationalcore/introduction-to-opencv/master/assets/haarcascade_frontalface_default.xml \
    -O haarcascade_frontalface_default.xml

image = cv2.imread('faces-1.jpg')
grey = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
faces = face_cascade.detectMultiScale(grey, 1.3, 5)
for (x,y,w,h) in faces:
     cv2.rectangle(image,(x,y),(x+w,y+h),(255,0,0),2)
plt.imshow(cv2.cvtColor(test_image, cv2.COLOR_BGR2RGB))